[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "beatbattle"
version = "0.1.0"
description = "An ai powered bot who plays beatbattle"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "librosa",
    "soundfile",
    "numpy",
    "scipy",
    "typer",
    "pydub"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
beatbattle = "beatbattle.cli:app"
